### ISSUE TITLE
Page builder not working?

### ISSUE THREAD

**Issue by mardianto** [bagusindrayana/goblog#2]
Page builder not working?
![Screenshot_12](https://user-images.githubusercontent.com/5848383/85912383-4c002e80-b856-11ea-9003-5032cba641c7.png)

**Comment by bagusindrayana** [comment]
ahh sorry,route conflict with directory inside public 
you can change route url in https://github.com/bagusindrayana/goblog/blob/master/routes/web.php#L31 
change it with a new url of this kind 
`Route::get("page/create/web-builder",'PageController@viewWebBuilder')->name("page.web-builder");` 
or another you want 

current url admin/web-builder is conflic with directory with same name in public

i will update this bug in next commit

**Comment by bagusindrayana** [comment]
i have new commit and update
inlude this bug and missing user_id in create new page

and add some new feature
-menu drag and drop like wordpres with this library https://github.com/harimayco/wmenu-builder
