### ISSUE TITLE
Menu Builder

### ISSUE THREAD

**Issue by kukuh21** [bagusindrayana/goblog#4]
Mas mau tanya, untuk implementasi menu builder di front end bagaimana ya pemanggilan url y,.
misal kita sudah bikin menu dengan nama "profile", lalu url y http://localhost/blog/profile
nah bagaimana caranya dengan url tersebut menuju page profile, apakah di setiap route di buat url "http://localhost/blog/profile" pada setiap page yg di panggil. Makasih

**Comment by bagusindrayana** [comment]
list data menu di generate otomatis di [layouts/layout.blade.php](https://github.com/bagusindrayana/goblog/blob/8223dfee881550fa3383731bf94f47f2b7a6536f/resources/views/layouts/app.blade.php#L47-L64) lewat fungsi  dari [app/Helpers/Helper.php](https://github.com/bagusindrayana/goblog/blob/8223dfee881550fa3383731bf94f47f2b7a6536f/app/Helpers/Helper.php#L124-L134)

jika ingin meredirect link menu ke halaman/post tertentu bisa di kostum url-slug halaman/postnya agar sesuai sama link yang ada di menu atau link yang ada di menu di sesuaikan dengan link halaman/post terkait

**Comment by bagusindrayana** [comment]
saya tidak tahu dengan maksud `apakah di setiap route di buat url "http://localhost/blog/profile" pada setiap page yg di panggil`, karena jika menggunakan sistem layouting menampilkan list link dari menu hanya sekali yaitu di file layoutnya saja
